# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710d261bd97a1538b53caf0e1c27fe6768f40282201074ccdf44639758b4af519bd48bdeb7bc540c6365ca562dec197331b07367ec13fc8cfa1df9f1c57fe0a4

test:
  secret_key_base: 508b42cfc1ff8de564d23f1b3c2875c4551015a036ab95ea9c6f7671128d54d77fd2b753782708427c3c246aedbf163fae440edb32568e27c3378691f4f4071c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
